version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend

  backend:
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - backend
      - frontend

  frontend:
    build: ./ui
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  frontend:
  backend:

